resolver: lts-8.21
packages:
  - katip
  - katip-elasticsearch
extra-deps:
  # These can be dropped probably as soon as they hit an LTS
  - bloodhound-0.15.0.2
  - http-types-0.12
flags:
  katip:
    lib-Werror: true
  katip-elasticsearch:
    lib-Werror: true
