resolver: lts-5.5
packages:
  - katip
  - katip-elasticsearch
extra-deps:
  - bloodhound-0.11.0.0
  - string-conv-0.1
  - aeson-0.11.1.0
  - criterion-1.1.0.0
  - attoparsec-0.13.0.1
  - rng-utils-0.2.1
  - retry-0.7.4
  - tasty-0.11.0.2
  - tagged-0.8.3
  - fail-4.9.0.0
  - uuid-1.3.12
flags:
  katip:
    lib-Werror: true
  katip-elasticsearch:
    lib-Werror: true
