resolver: lts-18.13
extra-deps:
  # ghc 8.8 support
  - github: wireapp/bloodhound
    commit: b409f52b518f20a4c20651b5893c31b7b85cb9b1
allow-newer: true
flags:
  katip-elasticsearch:
    lib-Werror: true
